<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Product>vsdbgmcp</Product>
    <Company>vsdbgmcp</Company>
    <Version>0.2.0</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
  </PropertyGroup>

</Project>
